spring.application.name=life-designer-backend

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

admin.email=admin@lifedesigner.com
admin.password=admin123

jwt.secret=YourVeryLongSecretKeyMustBeAtLeast32CharactersLong123456789
jwt.expiration=86400000

cloudinary.cloud-name=dgxdlocja
cloudinary.api-key=638428425537241
cloudinary.api-secret=y8LwBh2u99eRFFTHooE9URSUfxg

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=60MB

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080