spring.application.name=life-designer-backend

spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:life_designer_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=${DATABASE_DRIVER:org.h2.Driver}
spring.jpa.database-platform=${DATABASE_DIALECT:org.hibernate.dialect.H2Dialect}

admin.email=${DEFAULT_ADMIN_NAME:admin@example.com}
admin.password=${DEFAULT_ADMIN_PASSWORD:admin123}

jwt.secret=${SECRET_KEY:dGhpc2lzYXNlY3JldGtleWZvcmp3dHRva2VuZ2VuZXJhdGlvbjEyMzQ1Njc4OTA=}
jwt.expiration=${TOKEN_EXPIRATION:86400000}

cloudinary.cloud-name=${CLOUDINARY_NAME:dummy_cloud}
cloudinary.api-key=${CLOUDINARY_API_KEY:1234567890}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:dummy_secret}

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=60MB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080